export enum TomlState {
	Unknown = 0,
	Ok = 1,
	RequestTimeout = 2,
	DNSLookupFailed = 3,
	HostnameResolutionFailed = 4,
	ConnectionTimeout = 5,
	ConnectionRefused = 6,
	ConnectionResetByPeer = 7,
	SocketClosedPrematurely = 8,
	SocketTimeout = 9,
	HostUnreachable = 10,
	NotFound = 11,
	ParsingError = 12,
	Forbidden = 13,
	ServerError = 14,
	UnsupportedVersion = 15,
	UnspecifiedError = 16,
	ValidatorNotSEP20Linked = 17,
	EmptyValidatorsField = 18
}
