export enum TomlState {
	Unknown = 'Unknown',
	Ok = 'Ok',
	RequestTimeout = 'RequestTimeout',
	DNSLookupFailed = 'DNSLookupFailed',
	HostnameResolutionFailed = 'HostnameResolutionFailed',
	ConnectionTimeout = 'ConnectionTimeout',
	ConnectionRefused = 'ConnectionRefused',
	ConnectionResetByPeer = 'ConnectionResetByPeer',
	SocketClosedPrematurely = 'SocketClosedPrematurely',
	SocketTimeout = 'SocketTimeout',
	HostUnreachable = 'HostUnreachable',
	NotFound = 'NotFound',
	ParsingError = 'ParsingError',
	Forbidden = 'Forbidden',
	ServerError = 'ServerError',
	UnsupportedVersion = 'UnsupportedVersion',
	UnspecifiedError = 'UnspecifiedError',
	ValidatorNotSEP20Linked = 'ValidatorNotSEP20Linked',
	EmptyValidatorsField = 'EmptyValidatorsField'
}
